function getLibrary(){
    return [
        {"type":"Animation","property":"@keyframes","description":"Specifies the animation","version":3},
        {"type":"Animation","property":"animation","description":"A shorthand property for all the animation properties below, except the animation-play-state property","version":3},
        {"type":"Animation","property":"animation-name","description":"Specifies a name for the @keyframes animation","version":3},
        {"type":"Animation","property":"animation-duration","description":"Specifies how many seconds or milliseconds an animation takes to complete one cycle","version":3},
        {"type":"Animation","property":"animation-timing-function","description":"Specifies the speed curve of the animation","version":3},
        {"type":"Animation","property":"animation-delay","description":"Specifies when the animation will start","version":3},
        {"type":"Animation","property":"animation-iteration-count","description":"Specifies the number of times an animation should be played","version":3},
        {"type":"Animation","property":"animation-direction","description":"Specifies whether or not the animation should play in reverse on alternate cycles","version":3},
        {"type":"Animation","property":"animation-play-state","description":"Specifies whether the animation is running or paused","version":3},
        {"type":"Background","property":"background","description":"Sets all the background properties in one declaration","version":1},
        {"type":"Background","property":"background-attachment","description":"Sets whether a background image is fixed or scrolls with the rest of the page","version":1},
        {"type":"Background","property":"background-color","description":"Sets the background color of an element","version":1},
        {"type":"Background","property":"background-image","description":"Sets the background image for an element","version":1},
        {"type":"Background","property":"background-position","description":"Sets the starting position of a background image","version":1},
        {"type":"Background","property":"background-repeat","description":"Sets how a background image will be repeated","version":1},
        {"type":"Background","property":"background-clip","description":"Specifies the painting area of the background","version":3},
        {"type":"Background","property":"background-origin","description":"Specifies the positioning area of the background images","version":3},
        {"type":"Background","property":"background-size","description":"Specifies the size of the background images","version":3},
        {"type":"Border/Outline","property":"border","description":"Sets all the border properties in one declaration","version":1},
        {"type":"Border/Outline","property":"border-bottom","description":"Sets all the bottom border properties in one declaration","version":1},
        {"type":"Border/Outline","property":"border-bottom-color","description":"Sets the color of the bottom border","version":1 },
        {"type":"Border/Outline","property":"border-bottom-style","description":"Sets the style of the bottom border","version":1},
        {"type":"Border/Outline","property":"border-bottom-width","description":"Sets the width of the bottom border","version":1},
        {"type":"Border/Outline","property":"border-color","description":"Sets the color of the four borders","version":1},
        {"type":"Border/Outline","property":"border-left","description":"Sets all the left border properties in one declaration","version":1},
        {"type":"Border/Outline","property":"border-left-color","description":"Sets the color of the left border","version":1},
        {"type":"Border/Outline","property":"border-left-style","description":"Sets the style of the left border","version":1},
        {"type":"Border/Outline","property":"border-left-width","description":"Sets the width of the left border","version":1},
        {"type":"Border/Outline","property":"border-right","description":"Sets all the right border properties in one declaration","version":1},
        {"type":"Border/Outline","property":"border-right-color","description":"Sets the color of the right border","version":1},
        {"type":"Border/Outline","property":"border-right-style","description":"Sets the style of the right border","version":1},
        {"type":"Border/Outline","property":"border-right-width","description":"Sets the width of the right border","version":1},
        {"type":"Border/Outline","property":"border-style","description":"Sets the style of the four borders","version":1},
        {"type":"Border/Outline","property":"border-top","description":"Sets all the top border properties in one declaration","version":1},
        {"type":"Border/Outline","property":"border-top-color","description":"Sets the color of the top border","version":1},
        {"type":"Border/Outline","property":"border-top-style","description":"Sets the style of the top border","version":1},
        {"type":"Border/Outline","property":"border-top-width","description":"Sets the width of the top border","version":1},
        {"type":"Border/Outline","property":"border-width","description":"Sets the width of the four borders","version":1},
        {"type":"Border/Outline","property":"outline","description":"Sets all the outline properties in one declaration","version":2},
        {"type":"Border/Outline","property":"outline-color","description":"Sets the color of an outline","version":2},
        {"type":"Border/Outline","property":"outline-style","description":"Sets the style of an outline","version":2},
        {"type":"Border/Outline","property":"outline-width","description":"Sets the width of an outline","version":2},
        {"type":"Border/Outline","property":"border-bottom-left-radius","description":"Defines the shape of the border of the bottom-left corner","version":3},
        {"type":"Border/Outline","property":"border-bottom-right-radius","description":"Defines the shape of the border of the bottom-right corner","version":3},
        {"type":"Border/Outline","property":"border-image","description":"A shorthand property for setting all the border-image-* properties","version":3},
        {"type":"Border/Outline","property":"border-image-outset","description":"Specifies the amount by which the border image area extends beyond the border box","version":3},
        {"type":"Border/Outline","property":"border-image-repeat","description":"Specifies whether the image-border should be repeated, rounded or stretched","version":3},
        {"type":"Border/Outline","property":"border-image-slice","description":"Specifies the inward offsets of the image-border","version":3},
        {"type":"Border/Outline","property":"border-image-source","description":"Specifies an image to be used as a border","version":3},
        {"type":"Border/Outline","property":"border-image-width","description":"Specifies the widths of the image-border","version":3},
        {"type":"Border/Outline","property":"border-radius","description":"A shorthand property for setting all the four border-*-radius properties","version":3},
        {"type":"Border/Outline","property":"border-top-left-radius","description":"Defines the shape of the border of the top-left corner","version":3},
        {"type":"Border/Outline","property":"border-top-right-radius","description":"Defines the shape of the border of the top-right corner","version":3},
        {"type":"Border/Outline","property":"box-decoration-break","description":"","version":3},
        {"type":"Border/Outline","property":"box-shadow","description":"Attaches one or more drop-shadows to the box","version":3},
        {"type":"Box","property":"overflow-x","description":"Specifies whether or not to clip the left/right edges of the content, if it overflows the element's content area","version":3},
        {"type":"Box","property":"overflow-y","description":"Specifies whether or not to clip the top/bottom edges of the content, if it overflows the element's content area","version":3},
        {"type":"Box","property":"overflow-style","description":"Specifies the preferred scrolling method for elements that overflow","version":3},
        {"type":"Box","property":"rotation","description":"Rotates an element around a given point defined by the rotation-point property","version":3},
        {"type":"Box","property":"rotation-point","description":"Defines a point as an offset from the top left border edge","version":3},
        {"type":"Color","property":"color-profile","description":"Permits the specification of a source color profile other than the default","version":3},
        {"type":"Color","property":"opacity","description":"Sets the opacity level for an element","version":3},
        {"type":"Color","property":"rendering-intent","description":"Permits the specification of a color profile rendering intent other than the default","version":3},
        {"type":"Paged Media","property":"bookmark-label","description":"Specifies the label of the bookmark","version":3},
        {"type":"Paged Media","property":"bookmark-level","description":"Specifies the level of the bookmark","version":3},
        {"type":"Paged Media","property":"bookmark-target","description":"Specifies the target of the bookmark link","version":3},
        {"type":"Paged Media","property":"float-offset","description":"Pushes floated elements in the opposite direction of the where they have been floated with float","version":3},
        {"type":"Paged Media","property":"hyphenate-after","description":"Specifies the minimum number of characters in a hyphenated word after the hyphenation character","version":3},
        {"type":"Paged Media","property":"hyphenate-before","description":"Specifies the minimum number of characters in a hyphenated word before the hyphenation character","version":3},
        {"type":"Paged Media","property":"hyphenate-character","description":"Specifies a string that is shown when a hyphenate-break occurs","version":3},
        {"type":"Paged Media","property":"hyphenate-lines","description":"Indicates the maximum number of successive hyphenated lines in an element","version":3},
        {"type":"Paged Media","property":"hyphenate-resource","description":"Specifies a comma-separated list of external resources that can help the browser determine hyphenation points","version":3},
        {"type":"Paged Media","property":"hyphens","description":"Sets how to split words to improve the layout of paragraphs","version":3},
        {"type":"Paged Media","property":"image-resolution","description":"Specifies the correct resolution of images","version":3},
        {"type":"Paged Media","property":"marks","description":"Adds crop and/or cross marks to the document","version":3},
        {"type":"Paged Media","property":"string-set","description":"","version":3},
        {"type":"Dimension","property":"height","description":"Sets the height of an element","version":1},
        {"type":"Dimension","property":"max-height","description":"Sets the maximum height of an element","version":2},
        {"type":"Dimension","property":"max-width","description":"Sets the maximum width of an element","version":2},
        {"type":"Dimension","property":"min-height","description":"Sets the minimum height of an element","version":2},
        {"type":"Dimension","property":"min-width","description":"Sets the minimum width of an element","version":2},
        {"type":"Dimension","property":"width","description":"Sets the width of an element","version":1},
        {"type":"Flexible Box","property":"box-align","description":"Specifies how to align the child elements of a box","version":3},
        {"type":"Flexible Box","property":"box-direction","description":"Specifies in which direction the children of a box are displayed","version":3},
        {"type":"Flexible Box","property":"box-flex","description":"Specifies whether the children of a box is flexible or inflexible in size","version":3},
        {"type":"Flexible Box","property":"box-flex-group","description":"Assigns flexible elements to flex groups","version":3},
        {"type":"Flexible Box","property":"box-lines","description":"Specifies whether columns will go onto a new line whenever it runs out of space in the parent box","version":3},
        {"type":"Flexible Box","property":"box-ordinal-group","description":"Specifies the display order of the child elements of a box","version":3},
        {"type":"Flexible Box","property":"box-orient","description":"Specifies whether the children of a box should be laid out horizontally or vertically","version":3},
        {"type":"Flexible Box","property":"box-pack","description":"Specifies the horizontal position in horizontal boxes and the vertical position in vertical boxes","version":3},
        {"type":"Font","property":"font","description":"Sets all the font properties in one declaration","version":1},
        {"type":"Font","property":"font-family","description":"Specifies the font family for text","version":1},
        {"type":"Font","property":"font-size","description":"Specifies the font size of text","version":1},
        {"type":"Font","property":"font-style","description":"Specifies the font style for text","version":1},
        {"type":"Font","property":"font-variant","description":"Specifies whether or not a text should be displayed in a small-caps font","version":1},
        {"type":"Font","property":"font-weight","description":"Specifies the weight of a font","version":1},
        {"type":"Font","property":"@font-face","description":"A rule that allows websites to download and use fonts other than the web-safe fonts","version":3},
        {"type":"Font","property":"font-size-adjust","description":"Preserves the readability of text when font fallback occurs","version":3},
        {"type":"Font","property":"font-stretch","description":"Selects a normal, condensed, or expanded face from a font family","version":3},
        {"type":"Generated Content","property":"content","description":"Used with the :before and :after pseudo-elements, to insert generated content","version":2},
        {"type":"Generated Content","property":"counter-increment","description":"Increments one or more counters","version":2},
        {"type":"Generated Content","property":"counter-reset","description":"Creates or resets one or more counters","version":2},
        {"type":"Generated Content","property":"quotes","description":"Sets the type of quotation marks for embedded quotations","version":2},
        {"type":"Generated Content","property":"crop","description":"Allows a replaced element to be just a rectangular area of an object, instead of the whole object","version":3},
        {"type":"Generated Content","property":"move-to","description":"Causes an element to be removed from the flow and reinserted at a later point in the document","version":3},
        {"type":"Generated Content","property":"page-policy","description":"Determines which page-based occurance of a given element is applied to a counter or string value","version":3},
        {"type":"Grid","property":"grid-columns","description":"Specifies the width of each column in a grid","version":3},
        {"type":"Grid","property":"grid-rows","description":"Specifies the height of each column in a grid","version":3},
        {"type":"Hyperlink","property":"target","description":"A shorthand property for setting the target-name, target-new, and target-position properties","version":3},
        {"type":"Hyperlink","property":"target-name","description":"Specifies where to open links (target destination)","version":3},
        {"type":"Hyperlink","property":"target-new","description":"Specifies whether new destination links should open in a new window or in a new tab of an existing window","version":3},
        {"type":"Hyperlink","property":"target-position","description":"Specifies where new destination links should be placed","version":3},
        {"type":"Linebox","property":"alignment-adjust","description":"Allows more precise alignment of elements","version":3},
        {"type":"Linebox","property":"alignment-baseline","description":"Specifies how an inline-level element is aligned with respect to its parent","version":3},
        {"type":"Linebox","property":"baseline-shift","description":"Allows repositioning of the dominant-baseline relative to the dominant-baseline","version":3},
        {"type":"Linebox","property":"dominant-baseline","description":"Specifies a scaled-baseline-table","version":3},
        {"type":"Linebox","property":"drop-initial-after-adjust","description":"Sets the alignment point of the drop initial for the primary connection point","version":3},
        {"type":"Linebox","property":"drop-initial-after-align","description":"Sets which alignment line within the initial line box is used at the primary connection point with the initial letter box","version":3},
        {"type":"Linebox","property":"drop-initial-before-adjust","description":"Sets the alignment point of the drop initial for the secondary connection point","version":3},
        {"type":"Linebox","property":"drop-initial-before-align","description":"Sets which alignment line within the initial line box is used at the secondary connection point with the initial letter box","version":3},
        {"type":"Linebox","property":"drop-initial-size","description":"Controls the partial sinking of the initial letter","version":3},
        {"type":"Linebox","property":"drop-initial-value","description":"Activates a drop-initial effect","version":3 },
        {"type":"Linebox","property":"inline-box-align","description":"Sets which line of a multi-line inline block align with the previous and next inline elements within a line","version":3},
        {"type":"Linebox","property":"line-stacking","description":"A shorthand property for setting the line-stacking-strategy, line-stacking-ruby, and line-stacking-shift properties","version":3},
        {"type":"Linebox","property":"line-stacking-ruby","description":"Sets the line stacking method for block elements containing ruby annotation elements","version":3},
        {"type":"Linebox","property":"line-stacking-shift","description":"Sets the line stacking method for block elements containing elements with base-shift","version":3},
        {"type":"Linebox","property":"line-stacking-strategy","description":"Sets the line stacking strategy for stacked line boxes within a containing block element","version":3},
        {"type":"Linebox","property":"text-height","description":"Sets the block-progression dimension of the text content area of an inline box","version":3},
        {"type":"List","property":"list-style","description":"Sets all the properties for a list in one declaration","version":1},
        {"type":"List","property":"list-style-image","description":"Specifies an image as the list-item marker","version":1},
        {"type":"List","property":"list-style-position","description":"Specifies if the list-item markers should appear inside or outside the content flow","version":1},
        {"type":"List","property":"list-style-type","description":"Specifies the type of list-item marker","version":1},
        {"type":"Margin","property":"margin","description":"Sets all the margin properties in one declaration","version":1},
        {"type":"Margin","property":"margin-bottom","description":"Sets the bottom margin of an element","version":1},
        {"type":"Margin","property":"margin-left","description":"Sets the left margin of an element","version":1},
        {"type":"Margin","property":"margin-right","description":"Sets the right margin of an element","version":1},
        {"type":"Margin","property":"margin-top","description":"Sets the top margin of an element","version":1},
        {"type":"Marquee","property":"marquee-direction","description":"Sets the direction of the moving content","version":3},
        {"type":"Marquee","property":"marquee-play-count","description":"Sets how many times the content move","version":3},
        {"type":"Marquee","property":"marquee-speed","description":"Sets how fast the content scrolls","version":3},
        {"type":"Marquee","property":"marquee-style","description":"Sets the style of the moving content","version":3},
        {"type":"Multi column","property":"column-count","description":"Specifies the number of columns an element should be divided into","version":3},
        {"type":"Multi column","property":"column-fill","description":"Specifies how to fill columns","version":3},
        {"type":"Multi column","property":"column-gap","description":"Specifies the gap between the columns","version":3},
        {"type":"Multi column","property":"column-rule","description":"A shorthand property for setting all the column-rule-* properties","version":3},
        {"type":"Multi column","property":"column-rule-color","description":"Specifies the color of the rule between columns","version":3},
        {"type":"Multi column","property":"column-rule-style","description":"Specifies the style of the rule between columns","version":3},
        {"type":"Multi column","property":"column-rule-width","description":"Specifies the width of the rule between columns","version":3},
        {"type":"Multi column","property":"column-span","description":"Specifies how many columns an element should span across","version":3},
        {"type":"Multi column","property":"column-width","description":"Specifies the width of the columns","version":3},
        {"type":"Multi column","property":"columns","description":"A shorthand property for setting column-width and column-count","version":3},
        {"type":"Padding","property":"padding","description":"Sets all the padding properties in one declaration","version":1},
        {"type":"Padding","property":"padding-bottom","description":"Sets the bottom padding of an element","version":1},
        {"type":"Padding","property":"padding-left","description":"Sets the left padding of an element","version":1},
        {"type":"Padding","property":"padding-right","description":"Sets the right padding of an element","version":1},
        {"type":"Padding","property":"padding-top","description":"Sets the top padding of an element","version":1},
        {"type":"Paged media","property":"fit","description":"Gives a hint for how to scale a replaced element if neither its width nor its height property is auto","version":3},
        {"type":"Paged media","property":"fit-position","description":"Determines the alignment of the object inside the box","version":3},
        {"type":"Paged media","property":"image-orientation","description":"Specifies a rotation in the right or clockwise direction that a user agent applies to an image","version":3},
        {"type":"Paged media","property":"page","description":"Specifies a particular type of page where an element SHOULD be displayed","version":3},
        {"type":"Paged media","property":"size","description":"Specifies the size and orientation of the containing box for page content","version":3},
        {"type":"Positioning","property":"bottom","description":"Specifies the bottom position of a positioned element","version":2},
        {"type":"Positioning","property":"clear","description":"Specifies which sides of an element where other floating elements are not allowed","version":1},
        {"type":"Positioning","property":"clip","description":"Clips an absolutely positioned element","version":2},
        {"type":"Positioning","property":"cursor","description":"Specifies the type of cursor to be displayed","version":2},
        {"type":"Positioning","property":"display","description":"Specifies how a certain HTML element should be displayed","version":1},
        {"type":"Positioning","property":"float","description":"Specifies whether or not a box should float","version":1},
        {"type":"Positioning","property":"left","description":"Specifies the left position of a positioned element","version":2},
        {"type":"Positioning","property":"overflow","description":"Specifies what happens if content overflows an element's box","version":2},
        {"type":"Positioning","property":"position","description":"Specifies the type of positioning method used for an element (static, relative, absolute or fixed)","version":2},
        {"type":"Positioning","property":"right","description":"Specifies the right position of a positioned element","version":2},
        {"type":"Positioning","property":"top","description":"Specifies the top position of a positioned element","version":2},
        {"type":"Positioning","property":"visibility","description":"Specifies whether or not an element is visible","version":2},
        {"type":"Positioning","property":"z-index","description":"Sets the stack order of a positioned element","version":2},
        {"type":"Print","property":"orphans","description":"Sets the minimum number of lines that must be left at the bottom of a page when a page break occurs inside an element","version":2},
        {"type":"Print","property":"page-break-after","description":"Sets the page-breaking behavior after an element","version":2},
        {"type":"Print","property":"page-break-before","description":"Sets the page-breaking behavior before an element","version":2},
        {"type":"Print","property":"page-break-inside","description":"Sets the page-breaking behavior inside an element","version":2},
        {"type":"Print","property":"widows","description":"Sets the minimum number of lines that must be left at the top of a page when a page break occurs inside an element","version":2},
        {"type":"Ruby","property":"ruby-align","description":"Controls the text alignment of the ruby text and ruby base contents relative to each other","version":3},
        {"type":"Ruby","property":"ruby-overhang","description":"Determines whether, and on which side, ruby text is allowed to partially overhang any adjacent text in addition to its own base, when the ruby text is wider than the ruby base","version":3},
        {"type":"Ruby","property":"ruby-position","description":"Controls the position of the ruby text with respect to its base","version":3},
        {"type":"Ruby","property":"ruby-span","description":"Controls the spanning behavior of annotation elements","version":3},
        {"type":"Speech","property":"mark","description":"A shorthand property for setting the mark-before and mark-after properties","version":3},
        {"type":"Speech","property":"mark-after","description":"Allows named markers to be attached to the audio stream","version":3},
        {"type":"Speech","property":"mark-before","description":"Allows named markers to be attached to the audio stream","version":3},
        {"type":"Speech","property":"phonemes","description":"Specifies a phonetic pronunciation for the text contained by the corresponding element","version":3},
        {"type":"Speech","property":"rest","description":"A shorthand property for setting the rest-before and rest-after properties","version":3},
        {"type":"Speech","property":"rest-after","description":"Specifies a rest or prosodic boundary to be observed after speaking an element's content","version":3},
        {"type":"Speech","property":"rest-before","description":"Specifies a rest or prosodic boundary to be observed before speaking an element's content","version":3},
        {"type":"Speech","property":"voice-balance","description":"Specifies the balance between left and right channels","version":3},
        {"type":"Speech","property":"voice-duration","description":"Specifies how long it should take to render the selected element's content","version":3},
        {"type":"Speech","property":"voice-pitch","description":"Specifies the average pitch (a frequency) of the speaking voice","version":3},
        {"type":"Speech","property":"voice-pitch-range","description":"Specifies variation in average pitch","version":3},
        {"type":"Speech","property":"voice-rate","description":"Controls the speaking rate","version":3},
        {"type":"Speech","property":"voice-stress","description":"Indicates the strength of emphasis to be applied","version":3},
        {"type":"Speech","property":"voice-volume","description":"Refers to the amplitude of the waveform output by the speech synthesises","version":3},
        {"type":"Table","property":"border-collapse","description":"Specifies whether or not table borders should be collapsed","version":2},
        {"type":"Table","property":"border-spacing","description":"Specifies the distance between the borders of adjacent cells","version":2},
        {"type":"Table","property":"caption-side","description":"Specifies the placement of a table caption","version":2},
        {"type":"Table","property":"empty-cells","description":"Specifies whether or not to display borders and background on empty cells in a table","version":2},
        {"type":"Table","property":"table-layout","description":"Sets the layout algorithm to be used for a table","version":2},
        {"type":"Text","property":"color","description":"Sets the color of text","version":1},
        {"type":"Text","property":"direction","description":"Specifies the text direction/writing direction","version":2},
        {"type":"Text","property":"letter-spacing","description":"Increases or decreases the space between characters in a text","version":1},
        {"type":"Text","property":"line-height","description":"Sets the line height","version":1},
        {"type":"Text","property":"text-align","description":"Specifies the horizontal alignment of text","version":1},
        {"type":"Text","property":"text-decoration","description":"Specifies the decoration added to text","version":1},
        {"type":"Text","property":"text-indent","description":"Specifies the indentation of the first line in a text-block","version":1},
        {"type":"Text","property":"text-transform","description":"Controls the capitalization of text","version":1},
        {"type":"Text","property":"unicode-bidi","description":"","version":2},
        {"type":"Text","property":"vertical-align","description":"Sets the vertical alignment of an element","version":1},
        {"type":"Text","property":"white-space","description":"Specifies how white-space inside an element is handled","version":1},
        {"type":"Text","property":"word-spacing","description":"Increases or decreases the space between words in a text","version":1},
        {"type":"Text","property":"hanging-punctuation","description":"Specifies whether a punctuation character may be placed outside the line box","version":3},
        {"type":"Text","property":"punctuation-trim","description":"Specifies whether a punctuation character should be trimmed","version":3},
        {"type":"Text","property":"text-align-last","description":"Describes how the last line of a block or a line right before a forced line break is aligned when text-align is justify","version":3},
        {"type":"Text","property":"text-justify","description":"Specifies the justification method used when text-align is justify","version":3},
        {"type":"Text","property":"text-outline","description":"Specifies a text outline","version":3},
        {"type":"Text","property":"text-overflow","description":"Specifies what should happen when text overflows the containing element","version":3},
        {"type":"Text","property":"text-shadow","description":"Adds shadow to text","version":3},
        {"type":"Text","property":"text-wrap","description":"Specifies line breaking rules for text","version":3},
        {"type":"Text","property":"word-break","description":"Specifies line breaking rules for non-CJK scripts","version":3},
        {"type":"Text","property":"word-wrap","description":"Allows long, unbreakable words to be broken and wrap to the next line","version":3},
        {"type":"Transform 2d/3d","property":"transform","description":"Applies a 2D or 3D transformation to an element","version":3},
        {"type":"Transform 2d/3d","property":"transform-origin","description":"Allows you to change the position on transformed elements","version":3},
        {"type":"Transform 2d/3d","property":"transform-style","description":"Specifies how nested elements are rendered in 3D space","version":3},
        {"type":"Transform 2d/3d","property":"perspective","description":"Specifies the perspective on how 3D elements are viewed","version":3},
        {"type":"Transform 2d/3d","property":"perspective-origin","description":"Specifies the bottom position of 3D elements","version":3},
        {"type":"Transform 2d/3d","property":"backface-visibility","description":"Defines whether or not an element should be visible when not facing the screen","version":3},
        {"type":"Transition","property":"transition","description":"A shorthand property for setting the four transition properties","version":3},
        {"type":"Transition","property":"transition-property","description":"Specifies the name of the CSS property the transition effect is for","version":3},
        {"type":"Transition","property":"transition-duration","description":"Specifies how many seconds or milliseconds a transition effect takes to complete","version":3},
        {"type":"Transition","property":"transition-timing-function","description":"Specifies the speed curve of the transition effect","version":3},
        {"type":"Transition","property":"transition-delay","description":"Specifies when the transition effect will start","version":3},
        {"type":"User interface","property":"appearance","description":"Allows you to make an element look like a standard user interface element","version":3},
        {"type":"User interface","property":"box-sizing","description":"Allows you to define certain elements to fit an area in a certain way","version":3},
        {"type":"User interface","property":"icon","description":"Provides the author the ability to style an element with an iconic equivalent","version":3},
        {"type":"User interface","property":"nav-down","description":"Specifies where to navigate when using the arrow-down navigation key","version":3},
        {"type":"User interface","property":"nav-index","description":"Specifies the tabbing order for an element","version":3},
        {"type":"User interface","property":"nav-left","description":"Specifies where to navigate when using the arrow-left navigation key","version":3},
        {"type":"User interface","property":"nav-right","description":"Specifies where to navigate when using the arrow-right navigation key","version":3},
        {"type":"User interface","property":"nav-up","description":"Specifies where to navigate when using the arrow-up navigation key","version":3},
        {"type":"User interface","property":"outline-offset","description":"Offsets an outline, and draws it beyond the border edge","version":3},
        {"type":"User interface","property":"resize","description":"Specifies whether or not an element is resizable by the user","version":3}];
}